### ISSUE TITLE
how could I download it?

### ISSUE THREAD

**Issue by HolyTruth** [whereswaldon/build-v8-on-windows#1]
Excuse this , I've a little question here. When I finish building v8 with this, How could I download it from the actions? Can I use actions like remote desktop so that I could zip source code and upload them to some cloud?

**Comment by whereswaldon** [comment]
You'll need to modify the action to use something like this: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

I created this repo as a sort of experiment. I'm not able to offer end-user-support for it.
